cargo-features = ["profile-rustflags"]

[package]
name = "triangle-counting-lab"
version = "0.1.0"
edition = "2021"

[dependencies]
atoi_simd = "0.16.0"
bitvec = "1.0.1"
itertools = "0.13.0"
memmap2 = "0.9.4"
rayon = "1.10.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
