[package]
name = "triangle-counting-lab"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
rayon = "1.10.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
debug = false
